# Generated by Django 5.2.7 on 2025-10-26 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], max_length=20)),
                ('current_status', models.CharField(choices=[('student', 'Student'), ('working_professional', 'Working Professional')], max_length=30)),
                ('job_role', models.CharField(blank=True, max_length=100, null=True)),
                ('career_interest', models.CharField(max_length=200)),
                ('target_company', models.CharField(blank=True, max_length=100, null=True)),
                ('confident_skills', models.CharField(max_length=200)),
                ('face_encoding', models.BinaryField()),
            ],
        ),
    ]
